### ISSUE TITLE
Assign a licence

### ISSUE THREAD

**Issue by stevearm** [igorlg/batch-git-clone#1]
This tool looks cool, but if I want to use it at work I need to know it's licensed. Please choose one that suits you to make sharing easier.

You should just be able to drop in a [LICENCE.txt](https://github.com/stevearm/java-util/blob/master/LICENCE.txt) file

**Comment by igorlg** [comment]
Thanks for pointing this out!

I'm working on a major refactor, that includes making it into a PyPi package, but I'll add a license to its current state anyways!
